version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  executor: node
  ready:
    filters:
      branches:
        ignore: master
    type: approval
  chromatic-build-and-deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run build:storybook
        # 👇 Runs the Chromatic CLI
      - run: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --storybook-build-dir=storybook-static --exit-once-uploaded

workflows:
  chromatic-deploy:
    jobs:
      - chromatic-build-and-deploy:
          requires:
            - ready





